groups:
  default: '&d'
  admin: '&a'
  owner: '&e'


registeredCommands:
  - /msg
  - /broadcast
  - /say


emojis:
  - ':D@䰁'
  - ':)@䰀'
  - 'kızgın@䰂'
  - 'mahvol@䰃'
  - 'kalp@䰄'
  - 'kırıkkalp@䰅'
  - 'aşık@䰆'
  - 'öp@䰇'
  - 'ağla@䰈'
  - 'çapkın@䰉'
  - 'herneyse@䰊'
  - 'zz@䰋'
  - 'ölü@䰌'
  - ':|@䰍'
  - ';)@䰎'
  - ':(@䰏'
  - 'XD@䰐'
  - ':P@䰑'
  - ':O@䰒'
  - 'don@䰓'
  - ':/@䰔'
  - 'ahbe@䰕'
  - 'kırgınım@䰗'
  - 'umutsuz@䰘'
  - 'yes@䰙'
  - 'no@䰚'
  - 'ok@䰛'
  - 'mük@䰜'
  - 'mmt@䰝'
  - ':D2@䰞'
  - ':D3@䰟'
  - 'troll@䰠'
  - ':O2@䰡'
  - ':)ş@䰢'
  - ':(ş@䰣'
  - 'melek@䰤'
  - 'O.O@䰥'
  - 'yukarı@䰫'
  - 'assagi@䰬'
  - 'sol@䰭'
  - 'sag@䰮'
  - 'alkış@䰯'
  - 'hm@䰰'
  - 'elrisitas@䰱'
  - 'harold@䰲'
  - 'para@䰿'
  - 'pepelazer@䱷'
  - 'şapkaçıkar@䱸'
  - 'pepekahkaha@䱹'
  - 'pepemük@䱺'
  - 'pepeçapkın@䱻'
  - 'pepesıvamış@䱼'
  - 'pog@䱽'
  - '??@䱾'
  - 'ricardo@䱿'