name: OsEmojis
version: ${project.version}
main: com.minerival.develop.osemojis.OsEmojis
api-version: 1.16
authors: [OnwexryS]
commands:
  emoji:
    description: Emoji commands.
  el:
    description: Shortcut of emoji list
permissions:
  emoji.reload:
    default: op
  emoji.list:
    default: true
  el:
    default: true